In [1]:
import mne
import numpy as np
import pandas as pd
from model_functions import load_data, load_subject, subject_psd, epochs_psd, absolute_band_power, relative_band_power

In [2]:
import matplotlib
matplotlib.use('Qt5Agg')

In [3]:
raw = load_subject(50)
spectrum = subject_psd(raw,seg_length=4)

In [4]:
spectrum.plot()

<MNELineFigure size 1000x350 with 2 Axes>

In [5]:
epochs_spectrum = epochs_psd(raw,duration=30,overlap=15,seg_length=4)

In [6]:
for i in range(5):
    epochs_spectrum[i].plot()

In [7]:
raw.plot()

Using qt as 2D backend.


In [8]:
# spectrum.plot_topomap()

In [9]:
spectrum

<Power Spectrum (from Raw, welch method) | 19 channels × 179 freqs, 0.5-45.0 Hz>

In [10]:
spectrum_array = spectrum.get_data()
spectrum_array

array([[2.28093566e-09, 9.33255339e-10, 4.75026370e-10, ...,
        4.38682290e-13, 5.21550682e-13, 3.93865572e-13],
       [1.28954125e-09, 6.52236762e-10, 3.52098343e-10, ...,
        4.13025140e-13, 4.62358756e-13, 3.23638185e-13],
       [1.96022452e-09, 7.80615430e-10, 4.01024073e-10, ...,
        3.55025990e-13, 4.40772465e-13, 4.00615660e-13],
       ...,
       [1.17412480e-09, 6.30480554e-10, 3.64249655e-10, ...,
        2.08879267e-13, 2.38106591e-13, 1.64852482e-13],
       [1.22093516e-09, 6.38061127e-10, 3.73784868e-10, ...,
        1.48341639e-13, 1.70280378e-13, 1.21865074e-13],
       [1.23772795e-09, 6.47690719e-10, 3.75111852e-10, ...,
        1.94298979e-13, 2.17711774e-13, 1.47691858e-13]])

In [11]:
spectrum_array.shape

(19, 179)

In [12]:
spectrum_array, freqs = spectrum.get_data(return_freqs=True)

In [13]:
freqs

array([ 0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ,  2.25,  2.5 ,
        2.75,  3.  ,  3.25,  3.5 ,  3.75,  4.  ,  4.25,  4.5 ,  4.75,
        5.  ,  5.25,  5.5 ,  5.75,  6.  ,  6.25,  6.5 ,  6.75,  7.  ,
        7.25,  7.5 ,  7.75,  8.  ,  8.25,  8.5 ,  8.75,  9.  ,  9.25,
        9.5 ,  9.75, 10.  , 10.25, 10.5 , 10.75, 11.  , 11.25, 11.5 ,
       11.75, 12.  , 12.25, 12.5 , 12.75, 13.  , 13.25, 13.5 , 13.75,
       14.  , 14.25, 14.5 , 14.75, 15.  , 15.25, 15.5 , 15.75, 16.  ,
       16.25, 16.5 , 16.75, 17.  , 17.25, 17.5 , 17.75, 18.  , 18.25,
       18.5 , 18.75, 19.  , 19.25, 19.5 , 19.75, 20.  , 20.25, 20.5 ,
       20.75, 21.  , 21.25, 21.5 , 21.75, 22.  , 22.25, 22.5 , 22.75,
       23.  , 23.25, 23.5 , 23.75, 24.  , 24.25, 24.5 , 24.75, 25.  ,
       25.25, 25.5 , 25.75, 26.  , 26.25, 26.5 , 26.75, 27.  , 27.25,
       27.5 , 27.75, 28.  , 28.25, 28.5 , 28.75, 29.  , 29.25, 29.5 ,
       29.75, 30.  , 30.25, 30.5 , 30.75, 31.  , 31.25, 31.5 , 31.75,
       32.  , 32.25,

In [14]:
epochs_spectrum

<Power Spectrum (from Epochs, welch method) | 53 epochs × 19 channels × 179 freqs, 0.5-45.0 Hz>

In [15]:
epochs_array = epochs_spectrum.get_data()

In [16]:
epochs_array

array([[[1.88995264e-09, 9.30045334e-10, 2.06036839e-10, ...,
         2.93120381e-13, 6.76067503e-13, 9.52847976e-13],
        [1.83419370e-09, 9.23175959e-10, 2.81373493e-10, ...,
         1.76117982e-13, 2.88408545e-13, 3.96466417e-13],
        [1.95842513e-09, 8.86734611e-10, 2.23258816e-10, ...,
         3.99628047e-13, 4.08966221e-13, 4.99958433e-13],
        ...,
        [1.77762781e-09, 8.98119099e-10, 2.62594356e-10, ...,
         1.13700100e-13, 1.92822643e-13, 2.39958621e-13],
        [1.68870053e-09, 8.97371501e-10, 2.68717604e-10, ...,
         3.82952080e-14, 1.41976445e-13, 1.43124566e-13],
        [1.81384574e-09, 9.26925927e-10, 2.83127793e-10, ...,
         5.48872643e-14, 1.78950590e-13, 1.45523688e-13]],

       [[1.96417163e-09, 6.18300916e-10, 3.88938389e-10, ...,
         4.22573547e-13, 5.93594513e-13, 3.52711979e-13],
        [1.23153967e-09, 4.50104188e-10, 2.37330981e-10, ...,
         2.07705835e-13, 3.63403953e-13, 3.36441929e-13],
        [1.65988406e-09, 

In [17]:
epochs_array.shape

(53, 19, 179)

In [18]:
epochs_array,freqs = epochs_spectrum.get_data(return_freqs=True)

In [19]:
freqs

array([ 0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ,  2.25,  2.5 ,
        2.75,  3.  ,  3.25,  3.5 ,  3.75,  4.  ,  4.25,  4.5 ,  4.75,
        5.  ,  5.25,  5.5 ,  5.75,  6.  ,  6.25,  6.5 ,  6.75,  7.  ,
        7.25,  7.5 ,  7.75,  8.  ,  8.25,  8.5 ,  8.75,  9.  ,  9.25,
        9.5 ,  9.75, 10.  , 10.25, 10.5 , 10.75, 11.  , 11.25, 11.5 ,
       11.75, 12.  , 12.25, 12.5 , 12.75, 13.  , 13.25, 13.5 , 13.75,
       14.  , 14.25, 14.5 , 14.75, 15.  , 15.25, 15.5 , 15.75, 16.  ,
       16.25, 16.5 , 16.75, 17.  , 17.25, 17.5 , 17.75, 18.  , 18.25,
       18.5 , 18.75, 19.  , 19.25, 19.5 , 19.75, 20.  , 20.25, 20.5 ,
       20.75, 21.  , 21.25, 21.5 , 21.75, 22.  , 22.25, 22.5 , 22.75,
       23.  , 23.25, 23.5 , 23.75, 24.  , 24.25, 24.5 , 24.75, 25.  ,
       25.25, 25.5 , 25.75, 26.  , 26.25, 26.5 , 26.75, 27.  , 27.25,
       27.5 , 27.75, 28.  , 28.25, 28.5 , 28.75, 29.  , 29.25, 29.5 ,
       29.75, 30.  , 30.25, 30.5 , 30.75, 31.  , 31.25, 31.5 , 31.75,
       32.  , 32.25,

In [20]:
freq_bands = np.array([0.5,4.0,8.0,13.0,25.0,45.0])
abp = absolute_band_power(epochs_array,freqs,freq_bands)

In [21]:
abp

array([[[7.94938654e-10, 3.65934239e-11, 1.62665847e-11, 1.29736538e-11,
         1.39284631e-11],
        [7.61126189e-10, 3.65814445e-11, 1.35566869e-11, 9.19417765e-12,
         8.36282317e-12],
        [7.66128686e-10, 3.60461449e-11, 1.54025051e-11, 1.25115021e-11,
         1.50576874e-11],
        ...,
        [7.46033967e-10, 3.55964851e-11, 1.47180987e-11, 7.75564423e-12,
         5.25095413e-12],
        [7.43529368e-10, 3.52187187e-11, 1.37515680e-11, 7.38384322e-12,
         3.98897013e-12],
        [7.70190048e-10, 3.65147551e-11, 2.94121362e-11, 8.83301844e-12,
         4.53901369e-12]],

       [[7.27519896e-10, 4.93737266e-11, 1.34320679e-11, 1.05362142e-11,
         1.33226926e-11],
        [4.99271246e-10, 4.87019823e-11, 1.17073588e-11, 8.73788055e-12,
         8.17952310e-12],
        [6.63983067e-10, 4.74878345e-11, 1.38584195e-11, 1.11066579e-11,
         1.55394350e-11],
        ...,
        [4.59097049e-10, 4.76398103e-11, 1.28027616e-11, 7.31812198e-12,
        

In [22]:
abp.shape

(53, 19, 5)

In [23]:
print(np.min(abp),np.max(abp))

2.6233900801650157e-12 1.9174686354453907e-09


In [24]:
rbp1 = relative_band_power(epochs_array,freqs,freq_bands)

In [25]:
rbp1

array([[[0.9088121 , 0.04183536, 0.01859674, 0.0148321 , 0.01592369],
        [0.91832361, 0.04413671, 0.01635659, 0.01109308, 0.01009002],
        [0.90650398, 0.04265076, 0.01822466, 0.01480394, 0.01781666],
        ...,
        [0.92176342, 0.04398129, 0.01818497, 0.0095825 , 0.00648782],
        [0.92493449, 0.04381133, 0.01710665, 0.00918534, 0.00496219],
        [0.90665103, 0.04298438, 0.03462333, 0.01039804, 0.00534323]],

       [[0.89355645, 0.06064193, 0.01649757, 0.01294082, 0.01636323],
        [0.86589141, 0.08446436, 0.0203042 , 0.0151542 , 0.01418583],
        [0.88298507, 0.06315078, 0.01842935, 0.01476997, 0.02066482],
        ...,
        [0.86290839, 0.08954271, 0.02406378, 0.01375498, 0.00973014],
        [0.87268144, 0.09034687, 0.01703103, 0.01277722, 0.00716345],
        [0.85246301, 0.08951635, 0.03516804, 0.01449993, 0.00835266]],

       [[0.92551977, 0.03380105, 0.01426673, 0.01164261, 0.01476984],
        [0.91448179, 0.04391685, 0.01635872, 0.0133046 , 0.0

In [26]:
rbp1.shape

(53, 19, 5)

In [27]:
print(np.min(rbp1),np.max(rbp1))

0.0029538443536930173 0.9614760161364705


In [28]:
rbp2 = relative_band_power(*epochs_spectrum.get_data(return_freqs=True),freq_bands)

In [29]:
np.array_equal(rbp1,rbp2)

True